use Trenes_del_Nilo

------ Paso 1 -------

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE(),'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE(),'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE(),'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE(),'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE(),'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE(),'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE(),'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+1,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+1,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+1,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+1,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+1,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+1,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+1,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+2,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+2,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+2,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+2,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+2,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+2,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+2,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+3,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+3,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+3,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+3,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+3,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+3,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+3,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+4,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+4,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+4,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+4,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+4,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+4,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+4,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+5,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+5,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+5,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+5,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+5,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+5,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+5,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+6,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+6,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+6,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+6,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+6,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+6,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+6,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+7,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+7,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+7,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+7,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+7,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+7,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+7,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+8,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+8,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+8,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+8,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+8,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+8,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+8,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+9,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+9,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+9,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+9,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+9,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+9,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+9,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+10,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+10,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+10,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+10,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+10,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+10,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+10,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+11,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+11,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+11,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+11,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+11,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+11,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+11,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+12,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+12,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+12,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+12,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+12,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+12,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+12,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+13,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+13,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+13,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+13,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+13,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+13,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+13,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+14,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+14,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+14,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+14,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+14,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+14,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+14,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+15,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+15,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+15,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+15,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+15,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+15,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+15,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+16,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+16,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+16,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+16,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+16,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+16,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+16,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+17,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+17,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+17,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+17,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+17,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+17,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+17,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+18,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+18,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+18,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+18,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+18,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+18,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+18,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+19,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+19,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+19,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+19,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+19,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+19,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+19,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+20,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+20,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+20,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+20,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+20,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+20,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+20,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+21,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+21,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+21,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+21,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+21,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+21,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+21,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+22,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+22,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+22,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+22,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+22,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+22,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+22,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+23,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+23,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+23,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+23,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+23,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+23,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+23,'20:30','22:30')


insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+24,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+24,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+24,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+24,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+24,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+24,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+24,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+25,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+25,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+25,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+25,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+25,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+25,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+25,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+26,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+26,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+26,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+26,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+26,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+26,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+26,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+27,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+27,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+27,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+27,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+27,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+27,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+27,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+28,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+28,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+28,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+28,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+28,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+28,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+28,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+29,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+29,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+29,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+29,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+29,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+29,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+29,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+32,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+32,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+32,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+32,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+32,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+32,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+32,'20:30','22:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+33,'07:00','09:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+33,'09:15','11:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+33,'11:30','13:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+33,'13:45','15:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+33,'16:00','18:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Luxor','Cairo',GETDATE()+33,'18:15','20:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (1,'Cairo','Luxor',GETDATE()+33,'20:30','22:30')

------ Paso 2 -------

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE(),'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE(),'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE(),'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE(),'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE(),'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE(),'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE(),'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+1,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+1,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+1,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+1,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+1,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+1,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+1,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+2,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+2,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+2,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+2,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+2,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+2,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+2,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+3,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+3,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+3,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+3,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+3,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+3,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+3,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+4,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+4,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+4,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+4,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+4,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+4,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+4,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+5,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+5,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+5,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+5,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+5,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+5,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+5,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+6,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+6,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+6,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+6,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+6,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+6,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+6,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+7,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+7,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+7,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+7,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+7,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+7,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+7,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+8,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+8,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+8,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+8,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+8,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+8,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+8,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+9,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+9,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+9,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+9,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+9,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+9,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+9,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+10,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+10,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+10,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+10,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+10,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+10,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+10,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+11,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+11,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+11,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+11,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+11,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+11,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+11,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+12,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+12,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+12,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+12,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+12,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+12,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+12,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+13,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+13,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+13,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+13,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+13,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+13,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+13,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+14,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+14,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+14,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+14,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+14,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+14,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+14,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+15,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+15,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+15,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+15,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+15,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+15,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+15,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+16,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+16,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+16,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+16,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+16,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+16,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+16,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+17,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+17,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+17,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+17,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+17,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+17,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+17,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+18,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+18,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+18,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+18,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+18,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+18,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+18,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+19,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+19,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+19,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+19,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+19,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+19,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+19,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+20,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+20,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+20,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+20,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+20,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+20,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+20,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+21,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+21,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+21,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+21,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+21,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+21,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+21,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+22,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+22,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+22,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+22,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+22,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+22,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+22,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+23,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+23,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+23,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+23,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+23,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+23,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+23,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+24,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+24,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+24,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+24,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+24,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+24,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+24,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+25,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+25,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+25,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+25,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+25,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+25,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+25,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+26,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+26,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+26,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+26,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+26,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+26,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+26,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+27,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+27,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+27,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+27,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+27,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+27,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+27,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+28,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+28,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+28,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+28,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+28,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+28,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+28,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+29,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+29,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+29,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+29,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+29,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+29,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+29,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+32,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+32,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+32,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+32,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+32,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+32,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+32,'21:30','23:30')

insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+33,'08:00','10:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+33,'10:15','12:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+33,'12:30','14:30')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+33,'14:45','16:45')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+33,'17:00','19:00')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Cairo','Luxor',GETDATE()+33,'19:15','21:15')
insert into Viajes (Id_tren,Destino,Origen,Fecha_de_viaje,Horario_de_embarcacion,Horario_de_llegada) values (2,'Luxor','Cairo',GETDATE()+33,'21:30','23:30')
